Port riscv-tests to Dromajo
Condor-Performance-Modeling/dromajo pull request #17
Opened 2024-09-25 12:52 UTC by StanSofomoDev

PR for work related to https://sofomo.atlassian.net/browse/CN-64

2024-09-25 13:46 UTC, jeffnye-gh commented on tests/riscv_isa_test/Makefile
> +	@export RISCV_PREFIX=/tools/riscv64-unknown-elf/bin/riscv64-unknown-elf- && \
what's wrong with using the link in $TOP. so $RV_GNU_BAREMETAL_TOOLS/bin/riscv64-unknown-elf-

?

2024-09-25 14:48 UTC, StanSofomoDev commented
General Structure of Test Names:
rv: Stands for "RISC-V", indicating that these are RISC-V architecture tests.

64 or 32: Indicates the bit-width of the test. rv64 is for 64-bit RISC-V systems, and rv32 is for 32-bit systems.

ui, ua, um, etc.: These two-letter suffixes represent the ISA or instruction set extension being tested:

ui: User-level instructions (integer instructions)

ua: Atomic operations (A extension)

um: Multiplication and division instructions (M extension)

uz: Compressed instructions (Z extension)

uf: Floating-point operations (F extension)

uzbb: Bit manipulation (B extension)

uzba: Atomic bit manipulation

uzbc: Cryptographic extension

p or v: Indicates whether it's a standard (program-level) test or a vector test:

p: Typically program-level tests (standard user instructions)

v: Vector instruction set tests (vector extension)

Mnemonic: The instruction or functionality being tested, such as add, xor, fadd, etc.

2024-09-26 13:10 UTC, StanSofomoDev commented on tests/riscv_isa_test/Makefile
> +	@export RISCV_PREFIX=/tools/riscv64-unknown-elf/bin/riscv64-unknown-elf- && \
Resolved after discussion yesterday.

2024-09-26 13:13 UTC, StanSofomoDev commented
![image](https://github.com/user-attachments/assets/aace46ec-00f4-41c9-a453-a34223c567b5)

Tested a moment ago with freshly cloned repository.

2024-09-27 14:14 UTC, jeffnye-gh requested changes
can you add docs on how to turn on off tests and how to determine the tested vs untested riscv isa tests

2024-09-27 14:14 UTC, jeffnye-gh commented on README.md
Those env vars only need to get set for 'make regression', is that correct?

anyone should be able to build without those set as it used to do.

2024-09-27 14:14 UTC, jeffnye-gh commented on README.md
will there be some documentation on how to add/remove tests from what is executed w/ make regression ?

2024-09-27 14:14 UTC, jeffnye-gh commented on tests/riscv_isa_test/allowed_isa_tests.txt
> +rv64mi-p-breakpoint
the name of this file is odd. just call it isa_test_list.txt, or something similar and obvious

There should also be a list of untested riscv-tests. this would just be documentation.

2024-09-29 21:41 UTC, jeffnye-gh commented
Other notes which may/may not be duplicated:

building dromajo should not build riscv-tests, that includes not checking for RISCV etc.
riscv-test should only be built on make regress
riscv-test should not be built every time you type make regress

this is also true for all tests, the test sources should only be built when needed

riscv-test should not be generating stfs, the options are wrong.
```
Running test 25/237: ./riscv_isa_test/share/riscv-tests/isa/rv64ua-p-amoadd_w
Argument stf_essential_mode is deprecated                                                     <=============
csr_read: invalid CSR=0x744
ILLEGAL INSTR 044 PC:0x800000e0 ENC:0x74445073
ILLEGAL INSN FALLTHROUGH
Test ./riscv_isa_test/share/riscv-tests/isa/rv64ua-p-amoadd_w failed with exit code 1
Test duration: 0 seconds
```

2024-10-01 14:23 UTC, StanSofomoDev commented on README.md
Done

2024-10-01 14:24 UTC, StanSofomoDev commented on tests/riscv_isa_test/allowed_isa_tests.txt
> +rv64mi-p-breakpoint
Done

2024-10-05 22:41 UTC, jeffnye-gh requested changes
See the comment, it does not capture errors.

This is now a problem, I need to be able to add new tests, I can no longer wait for this to complete first.

2024-10-05 22:41 UTC, jeffnye-gh commented on README.md
> +
This is incorrect or misleading.
"The summary at the end provides the total number of tests run, the number passed or failed, and the execution times" this is in the section for riscv_isa_test but it refers to the 4 tests, not the multiple tests in riscv-isa-test.

Since this does not report the details of what was tested from riscv-isa-tests add a note telling where the test log is found.

Document what update_disabled_isa_tests_list.sh and run_isa_test_suite.sh" are used for

run_isa_test_suite.sh does not properly detect an error:
Warning: Test file ./test_files/share/riscv-tests/isa/#rv64si-p-dirty does not exist

Nor does regress with the same situation
Test project /data/users/jeffnye/condor/cpm.dromajo.riscv_tests/build/tests
    Start 1: stf_load_store_baremetal
1/4 Test #1: stf_load_store_baremetal .........   Passed    0.24 sec
    Start 2: stf_load_store_linux
2/4 Test #2: stf_load_store_linux .............   Passed   10.74 sec
    Start 3: stf_gen_ad_hoc
3/4 Test #3: stf_gen_ad_hoc ...................   Passed    4.65 sec
    Start 4: riscv_isa_test
4/4 Test #4: riscv_isa_test ...................   Passed   43.76 sec

100% tests passed, 0 tests failed out of 4

2024-10-05 22:41 UTC, jeffnye-gh commented on README.md
> +
You need to add a section on how to add custom tests. I can no longer wait for this part to finish first.

2024-10-08 11:28 UTC, StanSofomoDev commented on tests/isa_test_suite/disabled_isa_tests.txt
> +rv64uzba-v-sh2add
Fixed

2024-10-08 13:42 UTC, jeffnye-gh approved these changes
Please run benchmarks stf generation and then merge, see slack message.

2024-10-08 14:22 UTC, merged