doc cleanup, add sample elf for examples
Condor-Performance-Modeling/dromajo pull request #18
Opened 2024-09-25 14:51 UTC by jeffnye-gh

Moved the original read me to ESPERANTO_README.md
New README.md with updated docs

Switch cleanup in main
Add bmi_mm.bare.riscv and bmi_sanity.bare.riscv sample elfs Update the golden traces

2024-09-25 19:02 UTC, StanSofomoDev requested changes

2024-09-25 19:02 UTC, StanSofomoDev commented on tests/stf_gen/golden/golden.bz2
I don't think that this should be removed - doing that might be the reason why ad hoc stf_gen test is failing for you

2024-09-26 02:33 UTC, jeffnye-gh commented on ESPERANTO_README.md
> +MEMORY_START=0x15000000
fixed

2024-09-26 02:33 UTC, jeffnye-gh commented on ESPERANTO_README.md
> +The original contents of the read me are found in ORIGINAL_README.md
removed that paragraph, now starts with original Esperanto paragraph

2024-09-26 02:35 UTC, jeffnye-gh commented on tests/stf_gen/golden/golden.bz2
was not intended to be removed, added back.

this was not the reason ad hoc failed.

2024-09-26 02:45 UTC, jeffnye-gh commented on ESPERANTO_README.md
> +The original contents of the read me are found in ORIGINAL_README.md
deleted that section, now begins with the original Esperanto paragraph

2024-09-26 11:35 UTC, StanSofomoDev commented
@jeffnye-gh I think that you haven't pushed commit with recent fixes :)

2024-09-26 12:42 UTC, jeffnye-gh commented
> @jeffnye-gh I think that you haven't pushed commit with recent fixes :)

Check again, it was pushed 10 hours ago, I just did a fresh pull and switch and the changes are there.

commit 5ef0ea457941882159944362e1c397cc9a413e8a (HEAD -> jeffnye/doc_cleanup_for_ext_release, origin/jeffnye/doc_cleanup_for_ext_release)
Author: Jeff Nye <jeff@www.condorcomputing.com>
Date:   Wed Sep 25 21:37:06 2024 -0500

    review fixes

2024-09-26 12:47 UTC, merged