improve run riscv isa test suite.sh
Condor-Performance-Modeling/dromajo pull request #23
Opened 2024-10-16 20:42 UTC by StanSofomoDev

PR for https://sofomo.atlassian.net/browse/CN-81 and https://sofomo.atlassian.net/browse/CN-80

2024-10-16 21:21 UTC, jeffnye-gh requested changes

2024-10-16 21:21 UTC, jeffnye-gh commented on tests/isa_test_suite/run_riscv_isa_test_suite.sh
> +
why do i need this? just exit everything.

2024-10-16 21:21 UTC, jeffnye-gh commented on README.md
>    ```
this is only for people that update the sha for riscv tests right?

2024-10-16 21:21 UTC, jeffnye-gh commented on README.md
> +- **riscv_isa_test:** This test runs a suite of RISC-V ISA compliance tests using a predefined list of enabled tests. It simulates each test and evaluates the results to verify correct functionality.
and where do you tell me how to enable/disable tests?

2024-10-16 21:21 UTC, jeffnye-gh commented on README.md
>    ```
how does an end user know what this is for?

2024-10-16 22:04 UTC, StanSofomoDev commented on tests/isa_test_suite/run_riscv_isa_test_suite.sh
> +
Changed

2024-10-16 22:04 UTC, StanSofomoDev commented on README.md
>    ```
I've added information about it.

2024-10-16 22:05 UTC, StanSofomoDev commented on README.md
> +- **riscv_isa_test:** This test runs a suite of RISC-V ISA compliance tests using a predefined list of enabled tests. It simulates each test and evaluates the results to verify correct functionality.
Updated

2024-10-20 18:25 UTC, jeffnye-gh approved these changes

2024-10-20 18:26 UTC, jeffnye-gh commented
DO NOT MERGE THIS BRANCH.

I have merged this into a local branch which will be merged to main.

2024-10-20 20:51 UTC, merged