STF trace generation improvements
Condor-Performance-Modeling/dromajo pull request #3
Opened 2024-01-30 23:29 UTC by kathlenemagnus

Made several improvements to STF trace generations to capture more information and improve how the traceable region of a workload is specified.

Generated STF traces now include:
- Register reads
- Register writes
- Memory reads (excluding the implicit `tohost` read)
- Memory writes
- Privilege mode changes
- Trap (exception and interrupt) codes
- Program state records at the beginning of the trace and between noncontiguous sections

Two new parameters have been added to specify the traceable region of a workload:
- Added `--stf_tracepoint` parameter to enable tracepoint detection when generating STF traces. The start tracepoint instruction (`0x4033`, `xor x0, x0, x0`) will enable tracing. The stop tracepoint instruction (`0x10c033`, `xor x0, x1, x1) will stop tracing.
- Added `--stf_priv_modes <USHM|USH|US|U>` parameter to specify which privilege modes should be included in STF tracing (deprecates `--stf_no_priv_check`). Entering an allowed privilege mode will enable tracing. Entering a non-allowed privilege mode will disable tracing. 

If multiple conditions are specified, all conditions must be TRUE for tracing to be enabled. Only one condition needs to become FALSE to disable tracing.

If the traceable region is specified, tracing will be enabled or disabled after the current instruction is finished executing. This means that any instructions that cause the workload to enter the traceable region **will not be** included in the trace, while any instructions that cause the workload to exit the traceable region **will be** included in the trace. For example when tracing only user-mode, the instruction that causes the workload to exit user-mode (e.g. a faulting instruction) will be included in the trace, while the instruction that causes the workload to return to user-mode (e.g. a return) will not be included in the trace. 

With these new controls, it is now possible for a trace to contain non-contiguous sections of the workload. To support this, the program state (i.e. all register values) is now recorded whenever STF tracing is enabled. The program state will always be recorded at the beginning of the trace and will also be recorded between any non-contiguous sections (i.e. when tracing is reenabled after being disabled).

2024-01-30 23:42 UTC, kathlenemagnus commented on tests/stf_gen/run_bare_metal.sh
> -# clean /extract reference stf's
Since STF traces now capture more information, the size of the generated traces has increased. When I created a new `tests/stf_gen/golden/golden.bz2` it exceeded GitHub's file size limit of 100MB. However, the STF format is already compressed so taring the traces doesn't actually reduce the file sizes. I checked in each golden STF individually instead.

2024-01-31 19:30 UTC, kathlenemagnus commented
I want to regenerate the Dhrystone and CoreMark traces in `tests/stf_gen/golden`. What Dromajo parameters are needed to do that?

2024-02-02 23:07 UTC, jeffnye-gh commented on tests/stf_gen/run_bare_metal.sh
> -# clean /extract reference stf's
From  the call you were going to add a mode or cmd-line option configuration that does not add the new information. Then file size is not a concern.

These are .stf, so I don't understand what you mean, 'taring the traces doesn't actually reduce the file sizes'.  There is a 200:1 compression ratio. 

```
-rw-r--r-- 1 jeffnye ccusers   497491 Jan 31 21:47 golden.bz2
```
Unpacking give:
```
drwxr-xr-x 2 jeffnye ccusers        8 Feb  2 16:26 .
drwxr-xr-x 4 jeffnye ccusers        7 Jan 31 21:47 ..
-rw-r--r-- 1 jeffnye ccusers  5799144 Nov  2 09:26 bmi_mm.bare.stf
-rw-r--r-- 1 jeffnye ccusers   122838 Nov  2 09:26 bmi_towers.bare.stf
-rw-r--r-- 1 jeffnye ccusers 93873269 Nov  2 09:27 coremark_123_456_789_10.stf
-rw-r--r-- 1 jeffnye ccusers  3300493 Nov  2 09:27 dhry_riscv_1000.stf
-rw-r--r-- 1 jeffnye ccusers      669 Nov  2 10:23 illegal.stf
```

2024-02-02 23:07 UTC, jeffnye-gh commented
The original Olympia dromajo patch did not include either the start or end trace macros in the stf output.  

My stf version retained that characteristic. 

I'd prefer this version also retain the original characteristic and not include the stop macro in the trace.

2024-02-02 23:11 UTC, jeffnye-gh commented
> I want to regenerate the Dhrystone and CoreMark traces in `tests/stf_gen/golden`. What Dromajo parameters are needed to do that?

These are generated with dromajo running linux, the dromajo parameters are specified in the olympia traces readme.

The benchmark parameters are in the stf name. 1000 iterations for dhrystone, the coremark seeds were 123 456 789 10

2024-02-02 23:35 UTC, jeffnye-gh requested changes
Code is fine. I have suggested changes that will make this less intrusive to our flows and not require regeneration of our trace library. I believe these can be done without compromising your intent.

The stop macro comment, making the switch which enables the register and memory traffic default to off, these make it easy to integrate and keep our existing tests and process the same.

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/README.md
please retain a modified form of the comment, something like:

If your dromajo does not support  --stf_priv_modes modify the 
run_bare_metal.sh

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/run_bare_metal.sh
> +  $DRO $OPT --stf_trace traces/$i.zstf  elf/$i.riscv
ditto, keep the uncompressed versions, and add your new tests

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/run_bare_metal.sh
> +  diff traces/$i.zstf  golden/$i.zstf
ditto, keep the uncompressed versions, and add your new tests

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/run_bare_metal.sh
> +export OPT='--stf_tracepoint'
Shouldn't this be: export OPT='--stf_priv_modes USHM' to mimic --stf_no_priv_check ?

I am assuming when you add the switches to enable the register and memory data they will default to off/false and then this change above, along with removing the stop macro from the trace, will mimic what we have already. And everything in our trace library will not require re-generation.

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/Makefile
> +	-rm -f traces/*.zstf elf/*.riscv
same thing

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/Makefile
> +		diff traces/$$i.zstf golden/$$i.zstf; \
same thing

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/Makefile
> +		$(DRO) $(OPT) --stf_trace traces/$$i.zstf  elf/$$i.riscv; \
I'd prefer if you did not change our simple check schemes. 

You probably want a new set that check your new features.

2024-02-02 23:35 UTC, jeffnye-gh commented on tests/stf_gen/Makefile
> +OPT='--stf_tracepoint'
To be compatible with our goldenfiles, this needs to also include 

--stf_priv_modes USHM

2024-02-07 16:27 UTC, knute-mips commented on include/machine.h
> +    uint64_t     stf_count;                     // Number of traced instructions
Should these have default values?

2024-02-07 16:27 UTC, knute-mips commented on include/riscv_cpu.h
> +        target_ulong value;
Default values?

2024-02-14 21:03 UTC, kathlenemagnus commented
@jeffnye-gh I am working on making the changes you requested. I've added a new parameters `--stf_essential_mode` which excludes the tracing of register and memory accesses to reduce the trace size. I also changed the default behavior to not include the stop tracepoint in the generated trace and added a parameter `--stf_include_stop_tracepoint`.

However, there are still two differences in the generated traces.

1. The previous method of capturing memory accesses did not work as intended. The intent was to trace the last memory access of a load or store instruction, but instead the "tohost" read that checks if simulation should be stopped was captured for every instruction. You can see in the example below (from `golden/bmi_mm.bare.stf`) that the "tohost" read is captured for every instruction, even the load instruction.
```
INST32    8700      0000000080002544                              9107b783             ld          x15,-1776(x15) # 0x80004e50
                                     MEM READ          0000       0000000080001000     0000000000000000
INST32    8701      0000000080002548                              02f70733             mul         x14,x14,x15
                                     MEM READ          0000       0000000080001000     0000000000000000
INST32    8702      000000008000254c                              fec579e3             bgeu        x10,x12,0x8000253e
                                     MEM READ          0000       0000000080001000     0000000000000000
```
In this PR, I put in a fix to never capture the "tohost" read so the resulting traces are actually quite a bit smaller. Below is what the new version of the trace would contain with `--stf_essential_mode` set.
```
INST32    8700      0000000080002544                              9107b783             ld          x15,-1776(x15) # 0x80004e50
INST32    8701      0000000080002548                              02f70733             mul         x14,x14,x15
INST32    8702      000000008000254c                              fec579e3             bgeu        x10,x12,0x8000253e
```

2. The previous implementation of the traceable region detection (tracepoints and privilege mode checks) would close the trace whenever exiting the traceable region. This means that only the first traceable region of a workload would be captured. In this PR, trace generation can now capture multiple, non-contiguous traceable regions. In the STF regression, this affects the `illegal` workload, which includes a pair of start/stop tracepoints in the synchronous exception handling code that is executed several times. 

@jeffnye-gh, me know how you'd like these two scenarios handled. I can still make the new traces identical to the golden traces if you would prefer.

2024-02-14 21:24 UTC, kathlenemagnus commented on include/riscv_cpu.h
> +        target_ulong value;
Since I've provided a constructor for this struct, the default constructor is not available. Attempting to use the default constructor will cause a compilation error.

2024-02-14 21:25 UTC, kathlenemagnus commented on tests/stf_gen/Makefile
> +		$(DRO) $(OPT) --stf_trace traces/$$i.zstf  elf/$$i.riscv; \
I'll add separate tests for `zstf` and restore the original tests.

2024-02-15 02:03 UTC, jeffnye-gh commented
Hi Kathlene,

Given your findings I think we (condor) should regenerate our trace lib,
existing lib contents are incorrect.
So please implement both 1 and 2 as you intend, -> no tohost, proper
capture of non-contiguous traceable region.

best regards
Jeff

On Wed, Feb 14, 2024 at 3:03 PM Kathlene Magnus ***@***.***>
wrote:

> @jeffnye-gh <https://github.com/jeffnye-gh> I am working on making the
> changes you requested. I've added a new parameters --stf_essential_mode
> which excludes the tracing of register and memory accesses to reduce the
> trace size. I also changed the default behavior to not include the stop
> tracepoint in the generated trace and added a parameter
> --stf_include_stop_tracepoint.
>
> However, there are still two differences in the generated traces.
>
>    1. The previous method of capturing memory accesses did not work as
>    intended. The intent was to trace the last memory access of a load or store
>    instruction, but instead the "tohost" read that checks if simulation should
>    be stopped was captured for every instruction. You can see in the example
>    below (from golden/bmi_mm.bare.stf) that the "tohost" read is captured
>    for every instruction, even the load instruction.
>
> INST32    8700      0000000080002544                              9107b783             ld          x15,-1776(x15) # 0x80004e50
>                                      MEM READ          0000       0000000080001000     0000000000000000
> INST32    8701      0000000080002548                              02f70733             mul         x14,x14,x15
>                                      MEM READ          0000       0000000080001000     0000000000000000
> INST32    8702      000000008000254c                              fec579e3             bgeu        x10,x12,0x8000253e
>                                      MEM READ          0000       0000000080001000     0000000000000000
>
> In this PR, I put in a fix to never capture the "tohost" read so the
> resulting traces are actually quite a bit smaller. Below is what the new
> version of the trace would contain with --stf_essential_mode set.
>
> INST32    8700      0000000080002544                              9107b783             ld          x15,-1776(x15) # 0x80004e50
> INST32    8701      0000000080002548                              02f70733             mul         x14,x14,x15
> INST32    8702      000000008000254c                              fec579e3             bgeu        x10,x12,0x8000253e
>
>
>    1. The previous implementation of the traceable region detection
>    (tracepoints and privilege mode checks) would close the trace whenever
>    exiting the traceable region. This means that only the first traceable
>    region of a workload would be captured. In this PR, trace generation can
>    now capture multiple, non-contiguous traceable regions. In the STF
>    regression, this affects the illegal workload, which includes a pair
>    of start/stop tracepoints in the synchronous exception handling code that
>    is executed several times.
>
> @jeffnye-gh <https://github.com/jeffnye-gh>, me know how you'd like these
> two scenarios handled. I can still make the new traces identical to the
> golden traces if you would prefer.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#issuecomment-1944586004>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25MMC7BP55AOT6WLHCUKETYTURCFAVCNFSM6AAAAABCSDE3KGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBUGU4DMMBQGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-18 22:59 UTC, jeffnye-gh commented
Hi, are there additional changes to come for this PR?

On Wed, Feb 14, 2024 at 3:25 PM Kathlene Magnus ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/stf_gen/Makefile
> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#discussion_r1490086117>
> :
>
> > @@ -16,24 +13,22 @@ run:
>  	@echo "Generating traces"
>  	mkdir -p traces
>  	for i in $(bm_elfs); do \
> -		$(DRO) $(OPT) --stf_trace traces/$$i.stf  elf/$$i.riscv; \
> +		$(DRO) $(OPT) --stf_trace traces/$$i.zstf  elf/$$i.riscv; \
>
> I'll add separate tests for zstf and restore the original tests.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#discussion_r1490086117>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25MMC6QFZR4EP4OXKJ573TYTUTTXAVCNFSM6AAAAABCSDE3KGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBRGMZTMMJXGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-21 16:22 UTC, kathlenemagnus commented on tests/stf_gen/run_bare_metal.sh
> -# clean /extract reference stf's
I was missing a parameter when creating the tar. The new size of `golden.bz2` is well under thee 100MB limit.

2024-02-21 16:24 UTC, kathlenemagnus commented on tests/stf_gen/Makefile
> +OPT='--stf_tracepoint'
The default value for `--stf_priv_modes` is `USHM`, but I added it here anyways to be explicit.

2024-02-21 16:28 UTC, kathlenemagnus commented
@jeffnye-gh I just pushed my last set of changes. I just needed to finish updating the `stf_gen` regression. I updated the golden traces and added new tests for `zstf`. I believe I addressed all of your comments.

2024-02-21 16:31 UTC, kathlenemagnus commented on tests/stf_gen/run_bare_metal.sh
> +export OPT='--stf_tracepoint'
This is the list of parameters for the original `stf_gen` regression to mimic what is currently supported:
```--stf_essential_mode --stf_tracepoint --stf_priv_modes USHM```

Right now have the register and memory data collection default to on and the parameter `--stf_essential_mode` will disable the collection.

2024-02-25 23:44 UTC, jeffnye-gh commented
This has been merged into master (rather than the old [dromajo_stf_update](https://github.com/Condor-Performance-Modeling/dromajo/tree/jeffnye-gh/dromajo_stf_update) )

2024-02-25 23:48 UTC, jeffnye-gh commented
Hi Kathlene,

I have merged this PR with our master branch.

I did make a couple edits, some unrelated, but I commented out 1 zstf diff,
the files did not match. I believe it is related to the golden reference
rather than a functional problem. Let me know if you agree.


commit ff13255a50bd1b5e7597f3bf2ceaf24b782e8b72 (HEAD -> master,
origin/master, origin/HEAD)
Merge: f4ead00 a438bb4
Author: Jeff Nye ***@***.***>
Date:   Sun Feb 25 17:30:38 2024 -0600

    Merge branch 'kathlenemagnus/stf_improvements'

    This is merge of PR #3
    https://github.com/Condor-Performance-Modeling/dromajo/pull/3

    (Commented out 1 zstf test bmi_mm.bare.zstf failed comparison with
golden.)

    Authored-by: <kathlenemagnus>

    Other changes:

    Resolved minor conflicts with main branch.

    Minor fix for llx fprintf warning

    Modified CMakeLists to copy dromajo to bin/cpm_dromajo
    and to detect simpoint builds copying to bin/cpm_simpoint_dromajo

On Wed, Feb 21, 2024 at 10:31 AM Kathlene Magnus ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/stf_gen/run_bare_metal.sh
> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#discussion_r1497891699>
> :
>
> > @@ -1,8 +1,10 @@
>  #! /bin/bash
>
> -#change comment to not use stf_no_priv_check
> -export OPT='--stf_no_priv_check'
> -#export OPT
> +# TODO: Test without no parameters
> +# TODO: Test --stf_priv_modes parameter
> +
> +# Enabled tracepoint detection for testing
> +export OPT='--stf_tracepoint'
>
> This is the list of parameters for the original stf_gen regression to
> mimic what is currently supported:
> --stf_essential_mode --stf_tracepoint --stf_priv_modes USHM
>
> Right now have the register and memory data collection default to on and
> the parameter --stf_essential_mode will disable the collection.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#discussion_r1497891699>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25MMC7L3F2ILVQA3C5KE33YUYOO5AVCNFSM6AAAAABCSDE3KGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOJTG4ZTCMBTGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-27 04:30 UTC, jeffnye-gh commented
As luck would have it, we just noticed this, stf_check reports these errors.

Trace generator: Dromajo
Trace generator version: 1.1.0
Comment: Trace from Dromajo
Features: 0000000000080021
stf_check: ERROR INVALID_PHYS: Invalid phys PC value at index 1

This occurs on both essential and full traces.

Is there a fix for this?


On Sun, Feb 18, 2024 at 4:59 PM Jeff Nye ***@***.***> wrote:

> Hi, are there additional changes to come for this PR?
>
> On Wed, Feb 14, 2024 at 3:25 PM Kathlene Magnus ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In tests/stf_gen/Makefile
>> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#discussion_r1490086117>
>> :
>>
>> > @@ -16,24 +13,22 @@ run:
>>  	@echo "Generating traces"
>>  	mkdir -p traces
>>  	for i in $(bm_elfs); do \
>> -		$(DRO) $(OPT) --stf_trace traces/$$i.stf  elf/$$i.riscv; \
>> +		$(DRO) $(OPT) --stf_trace traces/$$i.zstf  elf/$$i.riscv; \
>>
>> I'll add separate tests for zstf and restore the original tests.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#discussion_r1490086117>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A25MMC6QFZR4EP4OXKJ573TYTUTTXAVCNFSM6AAAAABCSDE3KGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBRGMZTMMJXGY>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-02-27 04:32 UTC, jeffnye-gh commented
I do not know if messages are getting through, this could be a duplicate

"As luck would have it, we just noticed this, stf_check reports these errors.

Trace generator: Dromajo
Trace generator version: 1.1.0
Comment: Trace from Dromajo
Features: 0000000000080021
stf_check: ERROR INVALID_PHYS: Invalid phys PC value at index 1

This occurs on both essential and full traces.

Is there a fix for this?"

2024-02-27 15:06 UTC, knute-mips commented
I actually noticed this error on traces we've generated too.  I think this _might_ be a bug in `stf_check` but I haven't brought it to @bdutro 's attention.

2024-02-27 16:11 UTC, bdutro commented
The main issue here is that the traces have the `STF_CONTAIN_PHYSICAL_ADDRESS` feature set but don't contain any PTE records. I put together a tool that allows editing trace feature records, so you can use that to fix the checked-in traces without having to regenerate them.

Secondly, `stf_check` has a couple of overly-strict checks - one will fail if `STF_CONTAIN_PHYSICAL_ADDRESS` is not set, but can be bypassed with the `-n` flag. There's another that checks for non-zero memory access attributes, but that field is currently unused so I'm going to disable the check for now.

The fixes are pushed to `stf_tools`, so you'll just need to pull and rebuild. To disable the physical address feature in a trace, just do:
```
stf_disable_feature input.zstf output.zstf STF_CONTAIN_PHYSICAL_ADDRESS
```

2024-02-27 16:46 UTC, jeffnye-gh commented
ok, I'll give this a try. thank you.

On Tue, Feb 27, 2024 at 10:11 AM bdutro ***@***.***> wrote:

> The main issue here is that the traces have the
> STF_CONTAIN_PHYSICAL_ADDRESS feature set but don't contain any PTE
> records. I put together a tool that allows editing trace feature records,
> so you can use that to fix the checked-in traces without having to
> regenerate them.
>
> Secondly, stf_check has a couple of overly-strict checks - one will fail
> if STF_CONTAIN_PHYSICAL_ADDRESS is not set, but can be bypassed with the
> -n flag. There's another that checks for non-zero memory access
> attributes, but that field is currently unused so I'm going to disable the
> check for now.
>
> The fixes are pushed to stf_tools, so you'll just need to pull and
> rebuild. To disable the physical address feature in a trace, just do:
>
> stf_disable_feature input.zstf output.zstf STF_CONTAIN_PHYSICAL_ADDRESS
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Condor-Performance-Modeling/dromajo/pull/3#issuecomment-1966913304>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25MMCZBXTK4U5U3KNVEJNTYVYASHAVCNFSM6AAAAABCSDE3KGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRWHEYTGMZQGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-29 15:55 UTC, kathlenemagnus commented
@jeffnye-gh for the failing STF regression test (`bmi_mm.bare.zstf`), can you confirm the version of the STF lib you're pointing to? I can't recreate the fail on my machine.

Here's the STF lib version I'm using:
```
commit 69d48b1bab14a410c859aa3591b4eb175323ec98 (HEAD, master)
Merge: e605e82 a785f0f
Author: bdutro <brett.dutro@gmail.com>
Date:   Mon Jan 22 14:32:12 2024 -0600

    Merge pull request #24 from sparcians/dev/brettd/add-hardware-thread-id
    
    Rework ProcessIDExtRecord
```

2024-06-10 13:10 UTC, closed without merging

2024-06-10 13:10 UTC, jeffnye-gh commented
this was merged but not closed, closing PR